# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_AirConditioner.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        Form.setMinimumSize(QtCore.QSize(700, 500))
        Form.setMaximumSize(QtCore.QSize(700, 500))
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_control = QtWidgets.QWidget()
        self.page_control.setObjectName("page_control")
        self.label_temperature_target = QtWidgets.QLabel(self.page_control)
        self.label_temperature_target.setGeometry(QtCore.QRect(210, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_temperature_target.setFont(font)
        self.label_temperature_target.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temperature_target.setObjectName("label_temperature_target")
        self.pushButton_ON_OFF = QtWidgets.QPushButton(self.page_control)
        self.pushButton_ON_OFF.setGeometry(QtCore.QRect(470, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_ON_OFF.setFont(font)
        self.pushButton_ON_OFF.setObjectName("pushButton_ON_OFF")
        self.pushButton_instruction = QtWidgets.QPushButton(self.page_control)
        self.pushButton_instruction.setGeometry(QtCore.QRect(470, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_instruction.setFont(font)
        self.pushButton_instruction.setObjectName("pushButton_instruction")
        self.label_show_RoomId = QtWidgets.QLabel(self.page_control)
        self.label_show_RoomId.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_show_RoomId.setFont(font)
        self.label_show_RoomId.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_RoomId.setObjectName("label_show_RoomId")
        self.lcdNumber_temperature_current = QtWidgets.QLCDNumber(self.page_control)
        self.lcdNumber_temperature_current.setGeometry(QtCore.QRect(30, 230, 111, 71))
        self.lcdNumber_temperature_current.setDigitCount(4)
        self.lcdNumber_temperature_current.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_temperature_current.setObjectName("lcdNumber_temperature_current")
        self.label_speed_wind = QtWidgets.QLabel(self.page_control)
        self.label_speed_wind.setGeometry(QtCore.QRect(160, 340, 201, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.label_speed_wind.setFont(font)
        self.label_speed_wind.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed_wind.setObjectName("label_speed_wind")
        self.label_fee_current = QtWidgets.QLabel(self.page_control)
        self.label_fee_current.setGeometry(QtCore.QRect(170, 390, 201, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.label_fee_current.setFont(font)
        self.label_fee_current.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fee_current.setObjectName("label_fee_current")
        self.label_RoomId = QtWidgets.QLabel(self.page_control)
        self.label_RoomId.setGeometry(QtCore.QRect(170, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.label_RoomId.setFont(font)
        self.label_RoomId.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RoomId.setObjectName("label_RoomId")
        self.pushButton_add_wind = QtWidgets.QPushButton(self.page_control)
        self.pushButton_add_wind.setGeometry(QtCore.QRect(470, 340, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_add_wind.setFont(font)
        self.pushButton_add_wind.setObjectName("pushButton_add_wind")
        self.label_mode = QtWidgets.QLabel(self.page_control)
        self.label_mode.setGeometry(QtCore.QRect(170, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.label_mode.setFont(font)
        self.label_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mode.setObjectName("label_mode")
        self.lcdNumber_temperature_target = QtWidgets.QLCDNumber(self.page_control)
        self.lcdNumber_temperature_target.setGeometry(QtCore.QRect(210, 230, 111, 71))
        self.lcdNumber_temperature_target.setDigitCount(4)
        self.lcdNumber_temperature_target.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_temperature_target.setObjectName("lcdNumber_temperature_target")
        self.pushButton_sub_wind = QtWidgets.QPushButton(self.page_control)
        self.pushButton_sub_wind.setGeometry(QtCore.QRect(470, 420, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_sub_wind.setFont(font)
        self.pushButton_sub_wind.setObjectName("pushButton_sub_wind")
        self.label_show_fee_current = QtWidgets.QLabel(self.page_control)
        self.label_show_fee_current.setGeometry(QtCore.QRect(20, 390, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(14)
        self.label_show_fee_current.setFont(font)
        self.label_show_fee_current.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_fee_current.setObjectName("label_show_fee_current")
        self.pushButton_sub_temperature = QtWidgets.QPushButton(self.page_control)
        self.pushButton_sub_temperature.setGeometry(QtCore.QRect(470, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_sub_temperature.setFont(font)
        self.pushButton_sub_temperature.setObjectName("pushButton_sub_temperature")
        self.pushButton_add_temperature = QtWidgets.QPushButton(self.page_control)
        self.pushButton_add_temperature.setGeometry(QtCore.QRect(470, 180, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_add_temperature.setFont(font)
        self.pushButton_add_temperature.setObjectName("pushButton_add_temperature")
        self.label_show_temperature_current = QtWidgets.QLabel(self.page_control)
        self.label_show_temperature_current.setGeometry(QtCore.QRect(20, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_show_temperature_current.setFont(font)
        self.label_show_temperature_current.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_temperature_current.setObjectName("label_show_temperature_current")
        self.label_show_mode = QtWidgets.QLabel(self.page_control)
        self.label_show_mode.setGeometry(QtCore.QRect(20, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_show_mode.setFont(font)
        self.label_show_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_mode.setObjectName("label_show_mode")
        self.label_show_speed_wind = QtWidgets.QLabel(self.page_control)
        self.label_show_speed_wind.setGeometry(QtCore.QRect(20, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(18)
        self.label_show_speed_wind.setFont(font)
        self.label_show_speed_wind.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_speed_wind.setObjectName("label_show_speed_wind")
        self.label_fee_total = QtWidgets.QLabel(self.page_control)
        self.label_fee_total.setGeometry(QtCore.QRect(170, 440, 201, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.label_fee_total.setFont(font)
        self.label_fee_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fee_total.setObjectName("label_fee_total")
        self.label_show_fee_total = QtWidgets.QLabel(self.page_control)
        self.label_show_fee_total.setGeometry(QtCore.QRect(20, 440, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(14)
        self.label_show_fee_total.setFont(font)
        self.label_show_fee_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_fee_total.setObjectName("label_show_fee_total")
        self.stackedWidget.addWidget(self.page_control)
        self.page_instruction = QtWidgets.QWidget()
        self.page_instruction.setObjectName("page_instruction")
        self.textBrowser_instruction = QtWidgets.QTextBrowser(self.page_instruction)
        self.textBrowser_instruction.setGeometry(QtCore.QRect(0, 10, 691, 431))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textBrowser_instruction.setFont(font)
        self.textBrowser_instruction.setObjectName("textBrowser_instruction")
        self.pushButton_instruction_back = QtWidgets.QPushButton(self.page_instruction)
        self.pushButton_instruction_back.setGeometry(QtCore.QRect(550, 450, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_instruction_back.setFont(font)
        self.pushButton_instruction_back.setObjectName("pushButton_instruction_back")
        self.stackedWidget.addWidget(self.page_instruction)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_temperature_target.setText(_translate("Form", "目标温度"))
        self.pushButton_ON_OFF.setText(_translate("Form", "开关"))
        self.pushButton_instruction.setText(_translate("Form", "使用说明"))
        self.label_show_RoomId.setText(_translate("Form", "房间号"))
        self.label_speed_wind.setText(_translate("Form", "低/中/高速"))
        self.label_fee_current.setText(_translate("Form", "10.2"))
        self.label_RoomId.setText(_translate("Form", "12138"))
        self.pushButton_add_wind.setText(_translate("Form", "风速+"))
        self.label_mode.setText(_translate("Form", "制冷/制热"))
        self.pushButton_sub_wind.setText(_translate("Form", "风速-"))
        self.label_show_fee_current.setText(_translate("Form", "当前费用/元"))
        self.pushButton_sub_temperature.setText(_translate("Form", "温度-"))
        self.pushButton_add_temperature.setText(_translate("Form", "温度+"))
        self.label_show_temperature_current.setText(_translate("Form", "当前室温"))
        self.label_show_mode.setText(_translate("Form", "工作模式"))
        self.label_show_speed_wind.setText(_translate("Form", "风速"))
        self.label_fee_total.setText(_translate("Form", "100.2"))
        self.label_show_fee_total.setText(_translate("Form", "累计费用/元"))
        self.textBrowser_instruction.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'华文仿宋\';\">这里是使用方法+计费规则123ABC</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'华文仿宋\';\"><br /></p></body></html>"))
        self.pushButton_instruction_back.setText(_translate("Form", "返回"))
